### ISSUE TITLE
Where is the SourceTemplates.org project being developed?

### ISSUE THREAD

**Issue by mikkelee** [dovy/SourceTemplates#1]
Hi,

I'm trying to find information about the current state of the project and if possible, roadmap information. 

Some information exists on the sourcetemplates.org website, but without any dates making it hard to tell if anything has happened since October 2011.

Is it being done internally at this point only to be fully released when the spec is complete? Is it possible to keep up to date on progress?

Regards,
Mikkel Eide Eriksen

**Comment by dovy** [comment]
Mikkel:
It is very much a work in process. We had hoped to release the code earlier, but we are laboring to ensure that it's more accurate. 

If you would like you and I could interact directly via IM and I could tell you of status and progress.

**Comment by mikkelee** [comment]
Thanks for the response! I can be reached at mikkel dot eriksen at gmail - though I don't have any specific enquiries at the moment, I'm just curious as to the current state and expected completion.

**Comment by mikebronner** [comment]
Please add me as well. I am interested in more detailed ERDs. I am currently developing the structure in XCode Core Data for use with iOS and OS/X. I would be happy to share my core data file as a starter database, but it's not yet complete enough to work, and I want to make sure it is in-line with the guidelines before sharing.

You can email or IM me at mike do t bronner at rocking-mm d ot com.

Thanks!
~Mike
